### ISSUE TITLE
Server crash on 1.11.2 (dedicated server)

### ISSUE THREAD

**Issue by poswar** [MightyPirates/BedrockOres#16]
Crash occurred when running the machine on a dedicated server:
```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Pre
	at net.minecraftforge.client.MinecraftForgeClient.getRenderLayer(MinecraftForgeClient.java:52) ~[MinecraftForgeClient.class:?]
	at li.cil.bedrockores.common.block.BlockBedrockOre.func_176221_a(BlockBedrockOre.java:65) ~[BlockBedrockOre.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423) ~[atm$a.class:?]
	at li.cil.bedrockores.util.WorldUtils.playBreakSound(WorldUtils.java:22) ~[WorldUtils.class:?]
	at li.cil.bedrockores.common.tileentity.TileEntityBedrockMiner.updateExtraction(TileEntityBedrockMiner.java:442) ~[TileEntityBedrockMiner.class:?]
	at li.cil.bedrockores.common.tileentity.TileEntityBedrockMiner.func_73660_a(TileEntityBedrockMiner.java:128) ~[TileEntityBedrockMiner.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at net.minecraftforge.client.MinecraftForgeClient.getRenderLayer(MinecraftForgeClient.java:52) ~[MinecraftForgeClient.class:?]
	at li.cil.bedrockores.common.block.BlockBedrockOre.func_176221_a(BlockBedrockOre.java:65) ~[BlockBedrockOre.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423) ~[atm$a.class:?]
	at li.cil.bedrockores.util.WorldUtils.playBreakSound(WorldUtils.java:22) ~[WorldUtils.class:?]
	at li.cil.bedrockores.common.tileentity.TileEntityBedrockMiner.updateExtraction(TileEntityBedrockMiner.java:442) ~[TileEntityBedrockMiner.class:?]
	at li.cil.bedrockores.common.tileentity.TileEntityBedrockMiner.func_73660_a(TileEntityBedrockMiner.java:128) ~[TileEntityBedrockMiner.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by fnuecke** [comment]
Ahhh, crud. I wonder why it didn't crash when I tested it though... oh well. Should be fixed in version MC1.11.2-1.0.2.23. Either wait for Curse to approve or grab it from [the buildserver](http://ci.cil.li/job/BedrockOres-MC1.11/).
